In [1]:
import numpy as np
import pandas as pd

In [2]:
data_gs = pd.read_csv("./observations-gregtasney.csv")
data_gs.head()

C:\Users\lisa_\AppData\Local\Temp\ipykernel_32644\1662798607.py:1: DtypeWarning: Columns (15,26,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  data_gs = pd.read_csv("./observations-gregtasney.csv")

,id,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,created_at,updated_at,...,place_county_name,place_state_name,place_country_name,place_admin1_name,place_admin2_name,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id
0,26102174,Sun May 26 2019 07:56:38 GMT+1000 (GMT+10),2019-05-26,2019-05-25 21:56:38 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2019-05-31 06:25:48 UTC,2019-06-02 04:59:50 UTC,...,Salisbury,Queensland,Australia,Queensland,Salisbury,Argina astrea,Argina astrea,crotalaria pod borer,Insecta,318525.0
1,26102183,Sun May 19 2019 10:45:52 GMT+1000 (GMT+10),2019-05-19,2019-05-19 00:45:52 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2019-05-31 06:26:15 UTC,2022-10-18 09:01:06 UTC,...,Corinda,Queensland,Australia,Queensland,Corinda,Lesser Wanderer,Danaus petilia,Lesser Wanderer,Insecta,333775.0
2,26102189,Sun May 19 2019 10:37:34 GMT+1000 (GMT+10),2019-05-19,2019-05-19 00:37:34 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2019-05-31 06:26:36 UTC,2022-01-25 09:25:37 UTC,...,Corinda,Queensland,Australia,Queensland,Corinda,Blue Wanderer,Tirumala hamata,Blue Wanderer,Insecta,197078.0
3,26102706,NaN,NaN,NaN,Hawaii,1809954,gregtasney,Greg Tasney,2019-05-31 06:55:01 UTC,2023-04-27 13:22:35 UTC,...,Corinda,Queensland,Australia,Queensland,Corinda,Burnie Vine,Malaisia scandens,Burnie Vine,Plantae,705655.0
4,26102759,2019/05/01 8:04 PM HST,2019-05-01,2019-05-02 06:04:00 UTC,Hawaii,1809954,gregtasney,Greg Tasney,2019-05-31 06:57:25 UTC,2019-06-02 04:59:40 UTC,...,Salisbury,Queensland,Australia,Queensland,Salisbury,Argina astrea,Argina astrea,crotalaria pod borer,Insecta,318525.0

In [3]:
data_gs.tail()

,id,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,created_at,updated_at,...,place_county_name,place_state_name,place_country_name,place_admin1_name,place_admin2_name,species_guess,scientific_name,common_name,iconic_taxon_name,taxon_id
97612,192852297,2023-11-30 06:22:00,2023-11-30,2023-11-29 20:22:00 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2023-12-02 20:37:08 UTC,2023-12-04 03:02:00 UTC,...,Beaudesert - Pt C,Queensland,Australia,Queensland,Beaudesert - Pt C,Eastern Yellow Robin,Eopsaltria australis,Eastern Yellow Robin,Aves,14153.0
97613,192852406,2023-11-30 20:32:00,2023-11-30,2023-11-30 10:32:00 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2023-12-02 20:38:32 UTC,2023-12-04 08:24:19 UTC,...,Beaudesert - Pt C,Queensland,Australia,Queensland,Beaudesert - Pt C,Tusked Frog,Adelotus brevis,Tusked Frog,Amphibia,22084.0
97614,192852560,2023-11-29 19:11:00,2023-11-29,2023-11-29 09:11:00 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2023-12-02 20:40:21 UTC,2023-12-04 05:07:50 UTC,...,Beaudesert - Pt C,Queensland,Australia,Queensland,Beaudesert - Pt C,Rhinoceros Beetles,Adoryphorus coulonii,Red-headed Pasture Chafer,Insecta,490698.0
97615,192852761,2023-11-29 00:42:00,2023-11-29,2023-11-28 14:42:00 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2023-12-02 20:42:57 UTC,2023-12-04 08:25:27 UTC,...,Beaudesert - Pt C,Queensland,Australia,Queensland,Beaudesert - Pt C,Rainbow Lorikeet,Trichoglossus moluccanus,Rainbow Lorikeet,Aves,980095.0
97616,192856161,2023/11/27 7:14 AM,2023-11-27,2023-11-26 21:14:00 UTC,Brisbane,1809954,gregtasney,Greg Tasney,2023-12-02 21:17:20 UTC,2023-12-02 21:20:36 UTC,...,Boonah,Queensland,Australia,Queensland,Boonah,Solanum limitare,Solanum limitare,NaN,Plantae,1094817.0

In [4]:
data_gs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97617 entries, 0 to 97616
Data columns (total 42 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                97617 non-null  int64
 1   observed_on_string                97614 non-null  object
 2   observed_on                       97614 non-null  object
 3   time_observed_at                  97594 non-null  object
 4   time_zone                         97617 non-null  object
 5   user_id                           97617 non-null  int64
 6   user_login                        97617 non-null  object
 7   user_name                         97617 non-null  object
 8   created_at                        97617 non-null  object
 9   updated_at                        97617 non-null  object
 10  quality_grade                     97617 non-null  object
 11  license                           97617 non-null  object
 12  url                               97617 non-null  object
 13  image_url                         97501 non-null  object
 14  sound_url                         144 non-null    object
 15  tag_list                          19 non-null     object
 16  description                       4843 non-null   object
 17  num_identification_agreements     97617 non-null  int64
 18  num_identification_disagreements  97617 non-null  int64
 19  captive_cultivated                97617 non-null  bool
 20  oauth_application_id              12172 non-null  float64
 21  place_guess                       97311 non-null  object
 22  latitude                          97311 non-null  float64
 23  longitude                         97311 non-null  float64
 24  positional_accuracy               36605 non-null  float64
 25  public_positional_accuracy        38015 non-null  float64
 26  geoprivacy                        462 non-null    object
 27  taxon_geoprivacy                  33015 non-null  object
 28  coordinates_obscured              97617 non-null  bool
 29  positioning_method                73 non-null     object
 30  positioning_device                73 non-null     object
 31  place_town_name                   421 non-null    object
 32  place_county_name                 97296 non-null  object
 33  place_state_name                  97311 non-null  object
 34  place_country_name                97311 non-null  object
 35  place_admin1_name                 97311 non-null  object
 36  place_admin2_name                 97296 non-null  object
 37  species_guess                     96350 non-null  object
 38  scientific_name                   97616 non-null  object
 39  common_name                       80967 non-null  object
 40  iconic_taxon_name                 97615 non-null  object
 41  taxon_id                          97616 non-null  float64
dtypes: bool(2), float64(6), int64(4), object(30)
memory usage: 30.0+ MB